# Generated by Django 3.2.7 on 2022-10-07 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Starapp', '0003_post_author_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='like',
            field=models.BooleanField(default=False),
        ),
    ]
